//
//  DYPaypal.swift
//  PaypalPay
//
//  Created by Dan-YY on 2021-05-26.
//

import Foundation
import PayPalCheckout


@objc
class DYPaypalView: UIView {

	@objc
	override init(frame: CGRect) {
		super.init(frame: frame)
		commonInit()
	}

	required init?(coder: NSCoder) {
		fatalError("init(coder:) has not been implemented")
	}

	private func commonInit() {
		setupCheckoutConfig()
		setupPaypalButton()
		configurePayPalCheckout()
	}

	private func setupCheckoutConfig() {
		let config = CheckoutConfig(
			clientID: "", //YOUR_CLIENT_ID,
				returnUrl: "",//"YOUR_RETURN_URL",
				environment: .sandbox
		)

		Checkout.set(config: config)

	}

	private func setupPaypalButton() {
		let paymentButton = PayPalButton()
		paymentButton.frame = CGRect(x: 0.0, y: 0.0, width: 200, height: 50)
		addSubview(paymentButton)

	}

	private func configurePayPalCheckout() {
		Checkout.setCreateOrderCallback { createOrderAction in
			let amount = PurchaseUnit.Amount(currencyCode: .usd, value: "10.00")
			let purchaseUnit = PurchaseUnit(amount: amount)
			let order = OrderRequest(intent: .capture, purchaseUnits: [purchaseUnit])

			createOrderAction.create(order: order)
		}

		Checkout.setOnApproveCallback { approval in
			approval.actions.capture { (response, error) in
				print("Order successfully captured: \(String(describing: response?.data))")
			}
			// Success message when funds capture successfully.
		}

		Checkout.setOnCancelCallback {
			print("setOnCancelCallback")
			// User has cancelled the payment experience
		}

		Checkout.setOnErrorCallback { error in
			print("setOnErrorCallback", error)
			// Handle the error generated by the SDK
		}

	}

}
